---
- name: Install build slave1
  hosts: build
  become: yes

  tasks:
    - name: Ensure java package is present
      apt:
        name: default-jdk
        state: present
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
    - name: Ensure git package is present
      apt:
        name: git
        state: present
    - git:
        clone: yes
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /opt/
    - name: Ensure maven package
      command: mvn -f /opt/pom.xml package
    - name: Store artifact file into /opt/build
      fetch:
        src: /opt/target/hello-1.0.war
        dest: /opt/build
        flat: yes




- name: install prod slave2
  hosts: webserver
  become: yes

  tasks:
    - name: Ensure tomcat package
      apt:
        name: tomcat9
        state: present
    - name: Ensure tomcat service is started
      service:
        name: tomcat9
        state: started
    - name: Copy artifact file into tomcat
      copy:
        src: /opt/build/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/hello-1.0.war

